version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel3
    container_name: laravel3-container
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel

  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8086:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db
    networks:
      - laravel

  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "3400:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel3_db
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: your_password_here
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel

  

networks:
  laravel:

volumes:
  mysql-data:
